apiVersion: v1
kind: Service
metadata:
  name: eks-qa
  namespace: qa
  labels:
    app: eks-sample-linux-app
spec:
  selector:
    app: eks-sample-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 80000
  type: LoadBalancer

