apiVersion: v1
kind: Service
metadata:
  name: demo1
  
  
spec:
  selector:
    app.kubernetes.io/name: demo1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30005
  type: LoadBalancer
