apiVersion: v1
kind: Service
metadata:
  name: demo1
  
  
spec:
  selector:
    app.kubernetes.io/name: eks-sample-linux-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30006
  type: LoadBalancer
