apiVersion: v1
kind: Service
metadata:
  name: red
  namespace: dev
  labels:
    app: red
spec:
  selector:
    app.kubernetes.io/name: eks-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30003
  type: LoadBalancer
